package com.ydt.entity;
// Generated Dec 5, 2018 2:49:26 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObjectControlUserId generated by hbm2java
 */
@Embeddable
public class ObjectControlUserId implements java.io.Serializable {

	private int userId;
	private int objectControlId;

	public ObjectControlUserId() {
	}

	public ObjectControlUserId(int userId, int objectControlId) {
		this.userId = userId;
		this.objectControlId = objectControlId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "object_control_id", nullable = false)
	public int getObjectControlId() {
		return this.objectControlId;
	}

	public void setObjectControlId(int objectControlId) {
		this.objectControlId = objectControlId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ObjectControlUserId))
			return false;
		ObjectControlUserId castOther = (ObjectControlUserId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getObjectControlId() == castOther.getObjectControlId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getObjectControlId();
		return result;
	}

}
