package com.ydt.entity;
// Generated Dec 5, 2018 2:49:26 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ObjectControlUser generated by hbm2java
 */
@Entity
@Table(name = "object_control_user", catalog = "webshop1")
public class ObjectControlUser implements java.io.Serializable {

	private ObjectControlUserId id;
	private ObjectControl objectControl;
	private Users users;

	public ObjectControlUser() {
	}

	public ObjectControlUser(ObjectControlUserId id, ObjectControl objectControl, Users users) {
		this.id = id;
		this.objectControl = objectControl;
		this.users = users;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "objectControlId", column = @Column(name = "object_control_id", nullable = false)) })
	public ObjectControlUserId getId() {
		return this.id;
	}

	public void setId(ObjectControlUserId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "object_control_id", nullable = false, insertable = false, updatable = false)
	public ObjectControl getObjectControl() {
		return this.objectControl;
	}

	public void setObjectControl(ObjectControl objectControl) {
		this.objectControl = objectControl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
