package com.ydt.entity;
// Generated Dec 5, 2018 2:49:26 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoleObject generated by hbm2java
 */
@Entity
@Table(name = "role_object", catalog = "webshop1")
public class RoleObject implements java.io.Serializable {

	private RoleObjectId id;
	private ObjectsScreen objectsScreen;
	private Roles roles;

	public RoleObject() {
	}

	public RoleObject(RoleObjectId id, ObjectsScreen objectsScreen, Roles roles) {
		this.id = id;
		this.objectsScreen = objectsScreen;
		this.roles = roles;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false)),
			@AttributeOverride(name = "objectId", column = @Column(name = "object_id", nullable = false)) })
	public RoleObjectId getId() {
		return this.id;
	}

	public void setId(RoleObjectId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "object_id", nullable = false, insertable = false, updatable = false)
	public ObjectsScreen getObjectsScreen() {
		return this.objectsScreen;
	}

	public void setObjectsScreen(ObjectsScreen objectsScreen) {
		this.objectsScreen = objectsScreen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false, insertable = false, updatable = false)
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

}
