package com.ydt.entity;
// Generated Dec 5, 2018 2:49:26 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoleObjectId generated by hbm2java
 */
@Embeddable
public class RoleObjectId implements java.io.Serializable {

	private int roleId;
	private int objectId;

	public RoleObjectId() {
	}

	public RoleObjectId(int roleId, int objectId) {
		this.roleId = roleId;
		this.objectId = objectId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "object_id", nullable = false)
	public int getObjectId() {
		return this.objectId;
	}

	public void setObjectId(int objectId) {
		this.objectId = objectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleObjectId))
			return false;
		RoleObjectId castOther = (RoleObjectId) other;

		return (this.getRoleId() == castOther.getRoleId()) && (this.getObjectId() == castOther.getObjectId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleId();
		result = 37 * result + this.getObjectId();
		return result;
	}

}
