package com.ydt.entity;
// Generated Dec 5, 2018 2:49:26 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoleObjectControl generated by hbm2java
 */
@Entity
@Table(name = "role_object_control", catalog = "webshop1")
public class RoleObjectControl implements java.io.Serializable {

	private RoleObjectControlId id;
	private ObjectControl objectControl;
	private Roles roles;

	public RoleObjectControl() {
	}

	public RoleObjectControl(RoleObjectControlId id, ObjectControl objectControl, Roles roles) {
		this.id = id;
		this.objectControl = objectControl;
		this.roles = roles;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false)),
			@AttributeOverride(name = "objectControlId", column = @Column(name = "object_control_id", nullable = false)) })
	public RoleObjectControlId getId() {
		return this.id;
	}

	public void setId(RoleObjectControlId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "object_control_id", nullable = false, insertable = false, updatable = false)
	public ObjectControl getObjectControl() {
		return this.objectControl;
	}

	public void setObjectControl(ObjectControl objectControl) {
		this.objectControl = objectControl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false, insertable = false, updatable = false)
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

}
