package com.ydt.entity;
// Generated Dec 5, 2018 2:49:26 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoleObjectControlId generated by hbm2java
 */
@Embeddable
public class RoleObjectControlId implements java.io.Serializable {

	private int roleId;
	private int objectControlId;

	public RoleObjectControlId() {
	}

	public RoleObjectControlId(int roleId, int objectControlId) {
		this.roleId = roleId;
		this.objectControlId = objectControlId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "object_control_id", nullable = false)
	public int getObjectControlId() {
		return this.objectControlId;
	}

	public void setObjectControlId(int objectControlId) {
		this.objectControlId = objectControlId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleObjectControlId))
			return false;
		RoleObjectControlId castOther = (RoleObjectControlId) other;

		return (this.getRoleId() == castOther.getRoleId())
				&& (this.getObjectControlId() == castOther.getObjectControlId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleId();
		result = 37 * result + this.getObjectControlId();
		return result;
	}

}
