package com.ydt.entity;
// Generated Dec 5, 2018 2:49:26 PM by Hibernate Tools 5.0.6.Final

import com.fasterxml.jackson.annotation.*;
import org.hibernate.annotations.Proxy;

import java.util.*;
import javax.persistence.*;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "webshop1")
@Proxy(lazy = false)
public class Users implements java.io.Serializable {

	private int userId;
	private String fullName;
	private String password;
	private String userName;
	private int gioiTinh;
	private Date ngayBatDau;
	private Date ngaySinh;
	private String sdt;
	private String diaChi;
	private Department departments;
	private PositionUser positionUsers;
	private String email;
	@JsonIgnore
	private Set<ObjectControlUser> objectControlUsers = new HashSet<ObjectControlUser>(0);
	@JsonIgnore
	private Set<RoleUser> roleUsers = new HashSet<RoleUser>(0);

	private List<Roles> roles = new ArrayList<>();

	public Users() {
	}

	public Users(int userId, String fullName, String password, String userName) {
		this.userId = userId;
		this.fullName = fullName;
		this.password = password;
		this.userName = userName;
	}

	public Users(String fullName, String password, String userName) {
		this.fullName = fullName;
		this.password = password;
		this.userName = userName;
	}

	public Users(String fullName, String password, String userName, int gioiTinh, Date ngayBatDau, Date ngaySinh, String sdt, String diaChi, Department departments, PositionUser positionUsers,String email) {
		this.fullName = fullName;
		this.password = password;
		this.userName = userName;
		this.gioiTinh = gioiTinh;
		this.ngayBatDau = ngayBatDau;
		this.ngaySinh = ngaySinh;
		this.sdt = sdt;
		this.diaChi = diaChi;
		this.departments = departments;
		this.positionUsers = positionUsers;
		this.email = email;
	}

	public Users(int userId, String fullName, String password, String userName, int gioiTinh, Date ngayBatDau, Date ngaySinh, String sdt, String diaChi, Department departments, PositionUser positionUsers,String email) {
		this.userId = userId;
		this.fullName = fullName;
		this.password = password;
		this.userName = userName;
		this.gioiTinh = gioiTinh;
		this.ngayBatDau = ngayBatDau;
		this.ngaySinh = ngaySinh;
		this.sdt = sdt;
		this.diaChi = diaChi;
		this.departments = departments;
		this.positionUsers = positionUsers;
		this.email = email;
	}

	public int getGioiTinh() {
		return gioiTinh;
	}

	public void setGioiTinh(int gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Temporal(TemporalType.DATE)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy")
	public Date getNgayBatDau() {
		return ngayBatDau;
	}

	public void setNgayBatDau(Date ngayBatDau) {
		this.ngayBatDau = ngayBatDau;
	}

	@Temporal(TemporalType.DATE)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy")
	public Date getNgaySinh() {
		return ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	public String getSdt() {
		return sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	public String getDiaChi() {
		return diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	public Department getDepartments() {
		return departments;
	}

	public void setDepartments(Department departments) {
		this.departments = departments;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	public PositionUser getPositionUsers() {
		return positionUsers;
	}

	public void setPositionUsers(PositionUser positionUsers) {
		this.positionUsers = positionUsers;
	}

	public Users(int userId) {
		this.userId = userId;
	}

	public Users(int userId, String fullName, String password, String userName,
			Set<ObjectControlUser> objectControlUsers, Set<RoleUser> roleUsers) {
		this.userId = userId;
		this.fullName = fullName;
		this.password = password;
		this.userName = userName;
		this.objectControlUsers = objectControlUsers;
		this.roleUsers = roleUsers;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "full_name", length = 125)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "password", length = 225)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "user_name", length = 100)
	public String getUserName() {
		return this.userName;
	}

	@Column(name = "email")
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users",cascade= {CascadeType.PERSIST, CascadeType.REMOVE})
	public Set<ObjectControlUser> getObjectControlUsers() {
		return this.objectControlUsers;
	}

	public void setObjectControlUsers(Set<ObjectControlUser> objectControlUsers) {
		this.objectControlUsers = objectControlUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users",cascade= {CascadeType.PERSIST, CascadeType.REMOVE})
	public Set<RoleUser> getRoleUsers() {
		return this.roleUsers;
	}

	public void setRoleUsers(Set<RoleUser> roleUsers) {
		this.roleUsers = roleUsers;
	}
	@Transient
	public List<Roles> getRoles() {
		return roles;
	}

	public void setRoles(List<Roles> roles) {
		this.roles = roles;
	}
}
