package com.ydt.entity;
// Generated Dec 5, 2018 2:49:26 PM by Hibernate Tools 5.0.6.Final

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.hibernate.annotations.Proxy;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.*;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "webshop1")
@Proxy(lazy = false)
public class Users implements java.io.Serializable {

	private int userId;
	private String fullName;
	private String password;
	private String userName;
	@JsonIgnore
	private Set<ObjectControlUser> objectControlUsers = new HashSet<ObjectControlUser>(0);
	@JsonIgnore
	private Set<RoleUser> roleUsers = new HashSet<RoleUser>(0);

	private List<Roles> roles = new ArrayList<>();

	public Users() {
	}

	public Users(String fullName, String userName, String password) {
		this.fullName = fullName;
		this.userName = userName;
		this.password = password;
	}

	public Users(int userId) {
		this.userId = userId;
	}

	public Users(int userId, String fullName, String password, String userName,
			Set<ObjectControlUser> objectControlUsers, Set<RoleUser> roleUsers) {
		this.userId = userId;
		this.fullName = fullName;
		this.password = password;
		this.userName = userName;
		this.objectControlUsers = objectControlUsers;
		this.roleUsers = roleUsers;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "full_name", length = 125)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "password", length = 225)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "user_name", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<ObjectControlUser> getObjectControlUsers() {
		return this.objectControlUsers;
	}

	public void setObjectControlUsers(Set<ObjectControlUser> objectControlUsers) {
		this.objectControlUsers = objectControlUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<RoleUser> getRoleUsers() {
		return this.roleUsers;
	}

	public void setRoleUsers(Set<RoleUser> roleUsers) {
		this.roleUsers = roleUsers;
	}
	@Transient
	public List<Roles> getRoles() {
		return roles;
	}

	public void setRoles(List<Roles> roles) {
		this.roles = roles;
	}
}
